"use client";
import Link from "next/link";
import { FiClock, FiArrowRight, FiAlertTriangle } from "react-icons/fi";
import { useEffect, useState } from "react";
import { PageHead, Toast, useToast } from "@/components/ui";
import { closeDailyRegister, getComandas } from "@/services/comandas";
import type { Comanda } from "@/types/comanda";
import { localDay, money } from "@/utils/format";
export default function FecharDia() { const [items,setItems] = useState<Comanda[]>([]); const [confirm,setConfirm] = useState(false); const [done,setDone] = useState(false); const {toast,showToast} = useToast(); useEffect(()=>setItems(getComandas().filter(c=>localDay(c.abertaEm)===localDay(new Date()))),[]); const pagas=items.filter(c=>c.status==="PAGA"); const abertas=items.filter(c=>c.status==="ABERTA"); function finish() { try { closeDailyRegister(); setItems(getComandas().filter(c=>localDay(c.abertaEm)===localDay(new Date()))); setConfirm(false); setDone(true); showToast("Registro do dia fechado com sucesso."); } catch { showToast("Não foi possível fechar o registro."); } } return <div className="container inner-page"><PageHead eyebrow="FECHAMENTO DO MOVIMENTO" title="Fechar registro do dia." description="Confira o resumo antes de encerrar o movimento." back="/mais-opcoes"/>{done && <div className="notice success">Registro do dia fechado com sucesso. <Link href="/comandas-do-dia">Ver comandas <FiArrowRight aria-hidden="true" /></Link></div>}<div className="panel daily-panel"><div className="section-heading"><span className="section-icon"><FiClock aria-hidden="true" /></span><div><h2>Resumo de hoje</h2><p>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"full"}).format(new Date())}</p></div></div><div className="daily-grid"><div><span>Comandas pagas</span><strong>{pagas.length}</strong></div><div><span>Comandas abertas</span><strong>{abertas.length}</strong></div><div><span>Total recebido</span><strong>{money(pagas.reduce((s,c)=>s+c.total,0))}</strong></div><div><span>Total pendente</span><strong>{money(abertas.reduce((s,c)=>s+c.total,0))}</strong></div></div><div className="warning-box">Todas as comandas abertas de hoje serão marcadas como pendentes. Elas continuarão disponíveis para consulta.</div><button className="button danger" disabled={!abertas.length} onClick={()=>setConfirm(true)}>Fechar registro do dia <FiArrowRight aria-hidden="true" /></button>{!abertas.length && <p className="muted-note">Não há comandas abertas hoje para encerrar.</p>}</div>{confirm && <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="daily-title"><span className="modal-icon danger-icon"><FiAlertTriangle aria-hidden="true" /></span><h2 id="daily-title">Tem certeza que deseja fechar o registro do dia?</h2><p>{abertas.length} {abertas.length === 1 ? "comanda aberta será marcada" : "comandas abertas serão marcadas"} como pendente.</p><div className="modal-actions"><button className="button outline" onClick={()=>setConfirm(false)}>Cancelar</button><button className="button danger" onClick={finish}>Fechar registro do dia</button></div></div></div>}<Toast message={toast}/></div>; }

